//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_shastho.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advice
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string AdvisorName { get; set; }
        public string Email { get; set; }
        public string Reference { get; set; }
        public string Content { get; set; }
        public bool IsVerified { get; set; }
        public int Likes { get; set; }
        public int Dislikes { get; set; }
    }
}
